### ISSUE TITLE
Pakietyzacja, pom.xml i gałązka

### ISSUE THREAD

**Issue by WojTechM** [java-academy/diabelski-kod#1]
Przydadzą się poprawki w pakietach - zmiana na ja.workshops.clean_code lub coś w tym stylu.
Nazwa gałązki dev_drusill (moim zdaniem) powinna być zmieniona na coś w stylu clean_code_dojo
pom poprawić przy okazji zmiany pakietów
\<groupId>drusil\</groupId>
\<artifactId>APP\</artifactId>

**Comment by LIttleAncientForestKami** [comment]
Gałązka przemianowana. POMy poprawione, opis i nazwa do głównego POMa dodane. Wersje podbite. Ostrzeżenie o zduplikowanej zależności mockito-all naprawione, zależność usunięta. Pakiety zmienione.
